name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v3
        with:
          cache: true
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: npm run build
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v3
        with:
          cache: true
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: npm run lint
  check:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v3
        with:
          cache: true
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Compile Messages
        run: pnpm exec paraglide-js compile --project ./project.inlang --outdir ./src/lib/paraglide
      - name: Check
        run: npm run check
